#!/bin/bash -vx
VER=`git rev-parse --short HEAD`
BN="BuildNumber.txt"
if [ ! -e "$BN" ] ; then
    echo "1" > "$BN"
    VER=0
else
    VER=`cat $BN`
fi

VER=$((VER + 1))
echo "$VER" > "$BN"


sed -i "s/EXTRAVERSION =.*/EXTRAVERSION = $VER/g"  VERSION
